version: '3'
services:
  mysql:
    image: mysql:latest
    
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: javaApi
      MYSQL_USER: javaApi
      MYSQL_PASSWORD: javaApi
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
  java:
    build: .
    ports:
      - "6969:6969"
    depends_on:
      - mysql
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/conf/default.conf:/etc/nginx/conf.d/default.conf
  php:
    build:
      context: ./docker
    volumes:
      - ./:/var/www/html
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
